/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coffeemanagement;

import java.util.regex.Pattern;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import common.openPdf;
import dataaccessobject.CategoryDao;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import dataaccessobject.productDao;
import dataaccessobject.receiptDAO;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.product;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.TableModel;
import model.Category;
import model.Receipt;

/**
 *
 * @author RHADJEL
 */
public class PlaceOrder extends javax.swing.JFrame {

    public int billId = 1;
    public int totalAmnt = 0;
    public int productPrice = 0;
    public int productTotal = 0;
    public String emailPattern = "^[a-zA-Z0-9]+@[a-zA-Z0-9]+\\.[a-zA-Z0-9]+$";
    public String mobilePattern = "\\d{11}";
    public String userEmail;

    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() {
        initComponents();
    }

    public PlaceOrder(String email) {
        initComponents();
        cartBTN.setVisible(true);
        printBTN.setVisible(true);
        JFormattedTextField tf = ((JSpinner.DefaultEditor) jSpinner1.getEditor()).getTextField();
        tf.setEditable(false);

        jSpinner1.setModel(new SpinnerNumberModel(1, 1, 99, 1));

        userEmail = email;

    }

    public void productNameByCategory(String category) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<product> list = productDao.getAllRecordsByCategory(category);
        Iterator<product> itr = list.iterator();
        while (itr.hasNext()) {
            product productObj = itr.next();
            dtm.addRow(new Object[]{productObj.getName()});
        }
    }

    public void filterproductByName(String name, String category) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<product> list = productDao.filterproductByName(name, category);
        Iterator<product> itr = list.iterator();
        while (itr.hasNext()) {
            product productObj = itr.next();
            dtm.addRow(new Object[]{productObj.getName()});
        }
    }

    public void validateFields() {
        String customerName = nameCDTF.getText();
        String customerNumber = mobileCDTF.getText();
        String customerEmail = emailCDTF.getText();
        boolean isEmailValid = Pattern.matches(emailPattern, customerEmail);

        if (!customerEmail.isEmpty() && customerNumber.matches(mobilePattern) && customerNumber.length() == 11 && isEmailValid && totalAmnt > 0) {
            printBTN.setEnabled(true);
        } else {
            printBTN.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameCDTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mobileCDTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        billLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        PNameTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        PPriceTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PTotalTF = new javax.swing.JTextField();
        cartBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        totalALB = new javax.swing.JLabel();
        printBTN = new javax.swing.JButton();
        emailCDTF = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Oasis Cafe");
        setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1017, 28, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(48, 16, 16));
        jLabel2.setText("Bill ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 106, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(48, 16, 16));
        jLabel3.setText("Customer Details");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 143, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(48, 16, 16));
        jLabel4.setText("Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 173, -1, -1));

        nameCDTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameCDTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameCDTFKeyReleased(evt);
            }
        });
        getContentPane().add(nameCDTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 202, 250, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(48, 16, 16));
        jLabel5.setText("Mobile Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 235, -1, -1));

        mobileCDTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mobileCDTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobileCDTFKeyReleased(evt);
            }
        });
        getContentPane().add(mobileCDTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 262, 250, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(48, 16, 16));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 289, -1, -1));

        billLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        billLBL.setText("--");
        getContentPane().add(billLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 106, -1, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 262, 266, 356));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(48, 16, 16));
        jLabel10.setText("Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 106, -1, -1));

        PNameTF.setEditable(false);
        PNameTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(PNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 141, 218, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(48, 16, 16));
        jLabel11.setText("Price");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 106, -1, -1));

        PPriceTF.setEditable(false);
        PPriceTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(PPriceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 141, 218, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(48, 16, 16));
        jLabel12.setText("Quantity");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 173, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(48, 16, 16));
        jLabel13.setText("Total");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 173, -1, -1));

        PTotalTF.setEditable(false);
        PTotalTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PTotalTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTotalTFActionPerformed(evt);
            }
        });
        getContentPane().add(PTotalTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 202, 218, -1));

        cartBTN.setBackground(new java.awt.Color(181, 128, 25));
        cartBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cartBTN.setText("Add to Cart");
        cartBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartBTNActionPerformed(evt);
            }
        });
        getContentPane().add(cartBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(965, 230, -1, -1));

        jTable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 262, -1, 356));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Total Amount:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 624, -1, -1));

        totalALB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalALB.setText("00");
        getContentPane().add(totalALB, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 624, -1, -1));

        printBTN.setBackground(new java.awt.Color(181, 128, 25));
        printBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printBTN.setText("Place Order");
        printBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBTNActionPerformed(evt);
            }
        });
        getContentPane().add(printBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(966, 624, -1, -1));

        emailCDTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailCDTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailCDTFKeyReleased(evt);
            }
        });
        getContentPane().add(emailCDTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 312, 250, -1));

        jSpinner1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 202, 218, -1));

        jPanel1.setBackground(new java.awt.Color(196, 164, 132));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(48, 16, 16));
        jLabel1.setText("Place Order");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 22, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 199, 220, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(48, 16, 16));
        jLabel8.setText("Category");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 164, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Homepage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        billId = Integer.parseInt(receiptDAO.getId());
        billLBL.setText(receiptDAO.getId());
        ArrayList<Category> list = CategoryDao.getAllRecords();
        Iterator<Category> itr = list.iterator();
        while (itr.hasNext()) {
            Category categoryObj = itr.next();
            jComboBox1.addItem(categoryObj.getName());
        }
        String category = (String) jComboBox1.getSelectedItem();
        productNameByCategory(category);
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String ProductName = model.getValueAt(index, 0).toString();
        product product = productDao.getproductByname(ProductName);
        PNameTF.setText(product.getName());
        PPriceTF.setText(product.getPrice());
        jSpinner1.setValue(1);
        PTotalTF.setText(product.getPrice());
        productPrice = (int) Double.parseDouble(product.getPrice());
        productTotal = (int) Double.parseDouble(product.getPrice());

        int quantity = (Integer) jSpinner1.getValue();
        double productTotal = productPrice * quantity;

        PTotalTF.setText(String.format("%.2f", productTotal));
        productTotal = productPrice;
        cartBTN.setEnabled(true);

    }//GEN-LAST:event_jTable1MouseClicked

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:

        int quantity = (Integer) jSpinner1.getValue();
        if (quantity < 1) {
            jSpinner1.setValue(1);
            quantity = 1;
        }
        productTotal = productPrice * quantity;
        PTotalTF.setText(String.valueOf(productTotal));

    }//GEN-LAST:event_jSpinner1StateChanged

    private void printBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBTNActionPerformed
        // TODO add your handling code here:
        if (nameCDTF.getText().isEmpty() || mobileCDTF.getText().isEmpty() || emailCDTF.getText().isEmpty() || totalAmnt <= 0) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields and add products to the cart.");
            return;
        }
        String customerName = nameCDTF.getText();
        String mobileNumber = mobileCDTF.getText();
        String email = emailCDTF.getText();
        try {
            int billId = Integer.parseInt(receiptDAO.getId());
            Receipt receipt = new Receipt();
            receipt.setId(billId);
            receipt.setName(customerName);
            receipt.setMobileNumber(mobileNumber);
            receipt.setEmail(email);

            SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
            Date date = new Date();
            String todayDate = dFormat.format(date);
            receipt.setDate(todayDate);

            String total = String.valueOf(totalAmnt);
            receipt.setTotal(total);
            String createdBy = userEmail;
            receipt.setCreatedBy(createdBy);
            receiptDAO.save(receipt);

            // create docu
            String userHome = System.getProperty("user.home");
            String pdfFilePath = userHome + File.separator + "Desktop" + File.separator + "receipt_" + billId + ".pdf";

            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            PdfWriter.getInstance(doc, new FileOutputStream(pdfFilePath));
            doc.open();
            Paragraph cafeName = new Paragraph("                                                                       Oasis Cafe\n");
            doc.add(cafeName);
            Paragraph starLine = new Paragraph("************************************************************************************************************");
            doc.add(starLine);
            Paragraph paragraph3 = new Paragraph("\tReceipt id: " + billId + "\nCustomer Name: " + customerName + "\nTotal Paid: " + totalAmnt);
            doc.add(paragraph3);
            doc.add(starLine);
            PdfPTable tb1 = new PdfPTable(4);
            doc.add(tb1);
            tb1.addCell("Name");
            tb1.addCell("Price");
            tb1.addCell("Quantity");
            tb1.addCell("Total");
            for (int i = 0; i < jTable2.getRowCount(); i++) {
                String n = jTable2.getValueAt(i, 0).toString();
                String d = jTable2.getValueAt(i, 1).toString();
                String r = jTable2.getValueAt(i, 2).toString();
                String g = jTable2.getValueAt(i, 3).toString();
                tb1.addCell(n);
                tb1.addCell(d);
                tb1.addCell(r);
                tb1.addCell(g);
            }
            doc.add(tb1);
            doc.add(starLine);
            Paragraph tnxMsg = new Paragraph("Thank you! Please Visit Us Again");
            doc.add(tnxMsg);
            doc.close();
            // Open the PDF
            openPdf.openById(pdfFilePath);

            resetForm();
            JOptionPane.showMessageDialog(this, "Order placed successfully!");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_printBTNActionPerformed

    private void resetForm() {
        // Clear customer details and the cart
        nameCDTF.setText("");
        mobileCDTF.setText("");
        emailCDTF.setText("");
        DefaultTableModel cartTableModel = (DefaultTableModel) jTable2.getModel();
        cartTableModel.setRowCount(0);
        totalAmnt = 0;
        totalALB.setText("00");
        printBTN.setEnabled(false);

        // Update bill ID
        billLBL.setText(receiptDAO.getId());
    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String category = (String) jComboBox1.getSelectedItem();
        productNameByCategory(category);
        ArrayList<Category> list = CategoryDao.getAllRecords();

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void cartBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartBTNActionPerformed
        // TODO add your handling code here:

        if (PNameTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a product from the list.");
            return;
        }
        String name = PNameTF.getText();
        String price = PPriceTF.getText();
        String quantity = String.valueOf(jSpinner1.getValue());
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.addRow(new Object[]{name, price, quantity, productTotal});
        totalAmnt += productTotal;
        totalALB.setText(String.valueOf(totalAmnt));

        PNameTF.setText("");
        PPriceTF.setText("");
        jSpinner1.setValue(0);
        PTotalTF.setText("");

        validateFields();
        printBTN.setEnabled(true);
    }//GEN-LAST:event_cartBTNActionPerformed

    private void emailCDTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailCDTFKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_emailCDTFKeyReleased

    private void PTotalTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTotalTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PTotalTFActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int index = jTable2.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to remove this product?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            TableModel model = jTable2.getModel();
            String total = model.getValueAt(index, 3).toString();
            totalAmnt = totalAmnt - Integer.parseInt(total);
            totalALB.setText(String.valueOf(totalAmnt));
            ((DefaultTableModel) jTable2.getModel()).removeRow(index);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void nameCDTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameCDTFKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_nameCDTFKeyReleased

    private void mobileCDTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileCDTFKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_mobileCDTFKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PNameTF;
    private javax.swing.JTextField PPriceTF;
    private javax.swing.JTextField PTotalTF;
    private javax.swing.JLabel billLBL;
    private javax.swing.JButton cartBTN;
    private javax.swing.JTextField emailCDTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField mobileCDTF;
    private javax.swing.JTextField nameCDTF;
    private javax.swing.JButton printBTN;
    private javax.swing.JLabel totalALB;
    // End of variables declaration//GEN-END:variables
}
